name: contributors

on:
  push:
    branches:
      - master
      - main

jobs:
  contributor_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cjdenio/contributor_list@master
        with:
          commit_message: 'docs: update contributor list'
          max_contributors: 10